### ISSUE TITLE
how to create a semantic release using Github PRs

### ISSUE THREAD

**Issue by commonpike** [ProDemos/pds#7]
I tried to do this; but somehow allthough I to mentioned 'feat' in the github GUI on several places, it ends up as being named 'RELEASE'.

![Screenshot 2020-10-29 at 21 35 54](https://user-images.githubusercontent.com/3535798/97629722-c8866200-1a2e-11eb-8590-96801ce0d0d3.png)
![Screenshot 2020-10-29 at 21 36 07](https://user-images.githubusercontent.com/3535798/97629733-cb815280-1a2e-11eb-9deb-7f3c86985007.png)

eventually worked by merging develop into master locally (--no-ff), adding the message there and pushing that. but I'd like to use Github PRs.

**Comment by commonpike** [comment]
And then, it should actually be `feat:[space]foobar` in the commit message

[9:40:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat:Merge branch 'develop'
[9:40:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release

whereas

[9:49:19 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: space. Trying to create a new release !
[9:49:19 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor

(nb my normal commit messages actually make sense, but these didn't trigger releases)

I usually work with feature/bla branches and hotfix/bla branches, but it seems we can't make semantic releases look at merged branch names, only commit messages ..

**Comment by ddeboer** [comment]
Yeah, just follow https://www.conventionalcommits.org/en/v1.0.0/#summary and don’t worry.

**Comment by alexhebing** [comment]
In relation to PRs, I was thinking we could add this in `release.yml`:

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

(i.e. the idea is that we don't need 'feat:' in the PR title).

@ddeboer : would that work?

**Comment by ddeboer** [comment]
We currently have:

```yaml
on:
  push:
    branches:
      - master
```

so you’re adding the `pull_request` bit. That is a bad idea, because you don‘t want to publish releases when a change is merely a PR. You only want to release from master, _after_ the PR is merged to master.

>  the idea is that we don't need 'feat:' in the PR title

With our current config you don’t need the change type (such as `feat:` or `fix:`) in the PR title. Only _commit messages_ are checked. So you can leave it out of the PR title and add it to the final commit message in the squash dialog in GitHub’s GUI.

I prefer to add the change type to the PR title itself so I’m less likely to forget adding it to the final commit message, but the choice is yours.

**Comment by alexhebing** [comment]
> That is a bad idea, because you don‘t want to publish releases when a change is merely a PR. You only want to release from master, after the PR is merged to master.

Yes, you're right, I misunderstood the meaning / idea of `on pullrequest`.
